name: Node.js CI

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]
    name: Use Node.js ${{ matrix.node-version }}
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node enviroment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Npm
      run: npm install --force